// Generated by CoffeeScript 1.8.0
(function() {
  var Button, Channel, EndlessKnob, Fader, Knob;

  Knob = require('./knob');

  Fader = require('./fader');

  Button = require('./button');

  EndlessKnob = require('./endless_knob');

  Channel = (function() {
    Channel.prototype.knobs = [];

    Channel.prototype.fader = null;

    Channel.prototype.index = null;

    Channel.prototype.buttons = [];

    Channel.prototype.endless_knob = null;

    function Channel(channel) {
      this.index = channel;
      this.knobs = [0, 1, 2].map(function(knob) {
        return new Knob(channel, knob);
      });
      this.fader = new Fader(channel);
      this.buttons = [3, 4, 5, 6].map(function(button) {
        return new Button(channel, button);
      });
      this.endless_knob = new EndlessKnob(channel, {
        led: true
      });
    }

    return Channel;

  })();

  module.exports = Channel;

}).call(this);
