// Generated by CoffeeScript 1.8.0
(function() {
  var Button, EndlessKnob, EventEmitter, Led,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  Button = require('./button');

  Led = require('./led');

  EndlessKnob = (function(_super) {
    __extends(EndlessKnob, _super);

    EndlessKnob.prototype.led = null;

    EndlessKnob.prototype.button = null;

    function EndlessKnob(channel, options) {
      var button_position, _ref;
      if (options == null) {
        options = {};
      }
      this.channel = channel;
      this.position = [190, channel];
      this.button = new Button(0, 0);
      button_position = (_ref = options.button) != null ? _ref : 52 + channel;
      this.button.position_pressed[1] = button_position;
      this.button.position_released[1] = button_position;
      this.button.led = null;
      if (!options.led) {
        return;
      }
      this.led = new Led(4 + channel, 0);
    }

    EndlessKnob.prototype.updateValue = function(value) {
      if (value === 127) {
        value = -1;
      }
      return this.emit('update', value);
    };

    return EndlessKnob;

  })(EventEmitter);

  module.exports = EndlessKnob;

}).call(this);
