// Generated by CoffeeScript 1.8.0
(function() {
  var Component, Fader,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('./base-component');

  Fader = (function(_super) {
    __extends(Fader, _super);

    function Fader(channel) {
      this.channel = channel;
      this.position = [190, 16 + channel];
    }

    return Fader;

  })(Component);

  module.exports = Fader;

}).call(this);
