// Generated by CoffeeScript 1.8.0
(function() {
  var Led, initModule, ledPosition, led_color, xonek2;

  xonek2 = null;

  Led = (function() {
    Led.prototype.is_on = false;

    Led.prototype.color = null;

    function Led(channel, position) {
      initModule();
      this.position = ledPosition(channel, position);
    }

    Led.prototype.turn_on = function(color) {
      var msg;
      if (color == null) {
        color = xonek2.COLOR_RED;
      }
      this.is_on = true;
      this.color = color;
      msg = this.position.concat(127);
      msg[1] = led_color(msg[1], color);
      return xonek2.midi.output.sendMessage(msg);
    };

    Led.prototype.turn_off = function() {
      this.is_on = false;
      this.color = null;
      return xonek2.midi.output.sendMessage(this.position.concat(0));
    };

    return Led;

  })();

  initModule = function() {
    if (xonek2) {
      return;
    }
    return xonek2 = require('./xonek2');
  };

  ledPosition = function(channel, position) {
    var value;
    value = 48 + channel - (position * 4);
    return [158, value];
  };

  led_color = function(value, color) {
    var green, orange;
    orange = 36;
    if (value === 12 || value === 15) {
      orange = 4;
    }
    green = orange * 2;
    switch (color) {
      case xonek2.COLOR_RED:
        return value;
      case xonek2.COLOR_ORANGE:
        return value + orange;
      case xonek2.COLOR_GREEN:
        return value + green;
    }
  };

  module.exports = Led;

}).call(this);
